# Generated by Django 2.1.8 on 2019-05-18 12:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('term_in_months', models.IntegerField(validators=[django.core.validators.MaxValueValidator(360), django.core.validators.MinValueValidator(24)])),
                ('principal', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MinValueValidator(2000)])),
                ('interest_rate_pa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
