# Generated by Django 2.1.8 on 2019-05-18 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Loans', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loans',
            old_name='User',
            new_name='borrower',
        ),
    ]
