# Generated by Django 2.2 on 2019-05-19 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Loans', '0002_auto_20190518_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loans',
            old_name='interest_rate_pa',
            new_name='interest_rate_per_month',
        ),
    ]
